name: Publish to NPM

on:
  workflow_dispatch:
    inputs:
      component: 
        description: "Component (Package Name)"
        required: true
        type: choice
        options:
          - Button
          - Table

      release:
        description: "Release Type"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major
      custom-tag:
        description: "Custom Tag"
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: Map component to package
        run: |
          case "${{ inputs.component }}" in
            Button)
              echo "PACKAGE_NAME=@bln-design-system/button" >> $GITHUB_ENV
              ;;
            Table)
              echo "PACKAGE_NAME=@bln-design-system/table" >> $GITHUB_ENV
              ;;
            *)
              echo "Unknown component" && exit 1
              ;;
          esac
      
      - name: Install Dependencies
        run: pnpm --filter $PACKAGE_NAME install
      
      - name: Update Version
        run: pnpm --filter $PACKAGE_NAME version ${{ inputs.release }} 

      - name: 
        run: |
          if [ -z "${{ inputs.custom-tag }}" ]; then
            echo "Publishing with default tag (latest)"
            pnpm --filter $PACKAGE_NAME publish --access public
          else
            echo "Publishing with tag: ${{ inputs.custom-tag }}"
            pnpm --filter $PACKAGE_NAME publish --access public --tag ${{ inputs.custom-tag }}
          fi


