name: Publish to NPM

on:
  workflow_dispatch:
    inputs:
      component:
        description: "Component (Package Name)"
        required: true
        type: choice
        options:
          - Button
          - Table

      release:
        description: "Release Type"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major
      custom-tag:
        description: "Custom Tag"
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write 
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: Map component to package
        run: |
          case "${{ inputs.component }}" in
            Button)
              echo "PACKAGE_NAME=@bln-design-system/button" >> $GITHUB_ENV
              ;;
            Table)
              echo "PACKAGE_NAME=@bln-design-system/table" >> $GITHUB_ENV
              ;;
            *)
              echo "Unknown component" && exit 1
              ;;
          esac

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update Version
        run: |
          OUTPUT=$(pnpm --filter $PACKAGE_NAME exec npm version ${{ inputs.release }} --no-git-tag-version)
          VERSION=$(echo "$OUTPUT" | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+' | sed 's/^v//')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create Release PR
        run: |
          SAFE_NAME=$(echo "$PACKAGE_NAME" | sed 's/@//; s/\//-/g')
          BRANCH="release/${SAFE_NAME}-${VERSION}"

          git checkout -b "$BRANCH"

          git add .
          git commit -m ":bookmark: ${PACKAGE_NAME} ${VERSION}"
          git push origin "$BRANCH"

          gh pr create \
            --base main \
            --head "$BRANCH" \
            --title ":bookmark: ${PACKAGE_NAME} V${VERSION}" \
            --body "Automated release of ${PACKAGE_NAME} v${VERSION}"
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Publish
        run: |
          pnpm install --fronzen-lockfile
          if [ -z "${{ inputs.custom-tag }}" ]; then
            echo "Publishing with default tag (latest)"
            pnpm --filter $PACKAGE_NAME publish --access public --no-git-checks
          else
            echo "Publishing with tag: ${{ inputs.custom-tag }}"
            pnpm --filter $PACKAGE_NAME publish --access public --tag ${{ inputs.custom-tag }} --no-git-checks
          fi
